// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohboftfbhbjnitbroabz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9oYm9mdGZiaGJqbml0YnJvYWJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MzQwMzUsImV4cCI6MjA2OTIxMDAzNX0.bi9FXjp3n1xbBVPLG7bvx9N-rDrbF5HCYYzYF85uts0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});